excluded: # paths to ignore during linting. Takes precedence over `included`.
  - AEPCore/Tests
  - AEPCore/Mocks
  - AEPIdentity/Tests
  - AEPLifecycle/Tests
  - AEPServices/Tests
  - AEPServices/Mocks
  - AEPSignal/Tests
  - .build
  
included:
  - AEPCore
  - AEPIdentity
  - AEPLifecycle
  - AEPSignal
  - AEPServices

line_length: 1000

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - force_cast
  - todo
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - file_length
  - unused_optional_binding
  - implicit_getter
  - shorthand_operator
  - nesting
  - switch_case_alignment
  - orphaned_doc_comment
  - type_name
  - large_tuple
  - trailing_comma
  - type_body_length
  - trailing_whitespace
  - notification_center_detachment
  - for_where

analyzer_rules:
  - unused_import
